### ISSUE TITLE
question abount the inconsistency between "model_output_solution_correctness" and "model_output_solution_first_error_step"

### ISSUE THREAD

**Issue by Shijie-Xia** [dvlab-research/MR-GSM8K#1]
in './dataset/DiagGSM8K.json', why the _"model_output_solution_correctness"_ is wrong but _"model_output_solution_first_error_step"_ is N/A for  '4cfcac6e-240a-4d77-acc3-f6ae84e49940'  '349da39c-7a9c-4f6f-a289-a3cfe106922f' 'eb9b4726-62ce-4d84-93b9-f6650ae14a9b' 
<img width="676" alt="屏幕截图 2024-01-06 174807" src="https://github.com/dvlab-research/DiagGSM8K/assets/83998143/7313e691-1f57-4bd2-8272-f2ee90c135c7">
<img width="430" alt="屏幕截图 2024-01-06 174842" src="https://github.com/dvlab-research/DiagGSM8K/assets/83998143/21177188-3b4a-44d7-bf8c-1a032f53e8a0">
<img width="625" alt="屏幕截图 2024-01-06 174932" src="https://github.com/dvlab-research/DiagGSM8K/assets/83998143/815f6156-6054-42b7-af21-5e82ee9b83de">

**Comment by Shijie-Xia** [comment]
In your paper, it seems that there are only two classes: Correct, Incorrect with a labeled wrong step. But there are the third class in your dataset: incorrect without a labeled wrong step.

**Comment by Randolph-zeng** [comment]
Hi, thanks for your issue and this is exactly the kind of feedback I hope to get from the community! I apologize for the inconsistency despite our greatest effort to clean this dataset after a few rounds of manual cross validation. I have cleaned up the json file as you suggested. For both the field 'model_output_answer_correctness' and 'model_output_solution_correctness' there should be only two labels 'correct' and 'wrong'.
The huggingface dataset is also updated accordingly, please consider pull again from the repo

**Comment by Shijie-Xia** [comment]
It's solved! Thanks for your effort towards an aligned LLM
